// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwsnnwiwflsvsqiuzfja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3c25ud2l3ZmxzdnNxaXV6ZmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjUxNzYsImV4cCI6MjA3Mjg0MTE3Nn0._wkwx1DF3dU3prxTZ-w1jANj4uJS1u1tXzN4D4bq5wY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});